#!/bin/bash

mn=$(docker ps -a -q -f name="mininet")
mn_img=$(docker images -q iwaseyusuke/mininet)
odl=$(docker ps -a -q -f name="controller")
odl_img=$(docker images -q odl)

# Download and run the Mininet container

if [ -z "$mn" ]; then
    if [ -z "$mn_img" ]; then
        echo "Downloading the mininet image"
        sudo docker pull iwaseyusuke/mininet
    fi
    echo "Creating the mininet container"
    sudo docker create --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /lib/modules:/lib/modules --name mininet iwaseyusuke/mininet
fi

# Build and create (if not exists) the ODL container

if [ -z "$odl" ]; then
    if [ -z "$odl_img" ]; then
        echo "Creating the ODL container image"
        sudo docker build -t odl opendaylight/
    fi
    echo "Creating the ODL container"
    sudo docker run --name controller odl /home/bin/karaf
fi
