#!/bin/bash

TYPE=$1    # Type of test to run
SWITCH=$2  # Number of switch
HOST=$3    # Number of hosts
ATTACK=$4    # Type of DDoS attack

echo "Uploading the network"
docker cp -q networks.py mininet:/root/

echo "Uploading the simulations"
docker cp -q simulate.py mininet:/root/

python3 -c "from generate_flows import tree_flows; tree_flows($SWITCH, $HOST)"

docker exec -it mininet python3 /root/simulate.py $TYPE $SWITCH $HOST $ATTACK
