#!/bin/bash

TYPE=$1    # Type of test to run
SWITCH=$2  # Number of switch
HOST=$3    # Number of hosts
TIME=$4    # Time to test

echo "Uploading the network"
docker cp networks.py mininet:/root/
echo ""

echo "Uploading the simulations"
docker cp simulate.py mininet:/root/
echo ""

echo "Uploading the flows"
python3 -c "from generate_flows import tree_flows; tree_flows($HOST, $SWITCH)"
echo ""

echo "Running the test"
docker exec -it mininet python3 /root/simulate.py $TYPE $SWITCH $HOST $TIME
